import type { FoodCatalogRepository } from '../../repositories/contracts/food-catalog-repository'
import type { UpsertFoodCatalogInput } from '../../repositories/contracts/food-catalog-repository'

const MEDIUM_CURATED_CATALOG: UpsertFoodCatalogInput[] = [
  {
    canonicalName: 'banana prata',
    foodGroup: 'FRUIT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 98,
    protein: 1.3,
    carbs: 26,
    fat: 0.1,
    fiber: 2,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['banana', 'banana media', 'banana prata'],
  },
  {
    canonicalName: 'maca',
    foodGroup: 'FRUIT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 84,
    protein: 0.3,
    carbs: 22,
    fat: 0.2,
    fiber: 2,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['maca', 'maça', 'maçã'],
  },
  {
    canonicalName: 'pera',
    foodGroup: 'FRUIT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 96,
    protein: 0.4,
    carbs: 26,
    fat: 0.2,
    fiber: 3,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['pera'],
  },
  {
    canonicalName: 'goiaba',
    foodGroup: 'FRUIT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 54,
    protein: 1,
    carbs: 13,
    fat: 0.4,
    fiber: 6,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['goiaba'],
  },
  {
    canonicalName: 'mamao',
    foodGroup: 'FRUIT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 45,
    protein: 0.6,
    carbs: 11,
    fat: 0.1,
    fiber: 1.8,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['mamao', 'mamão'],
  },
  {
    canonicalName: 'abacaxi',
    foodGroup: 'FRUIT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 50,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    fiber: 1.4,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['abacaxi'],
  },
  {
    canonicalName: 'morango',
    foodGroup: 'FRUIT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 30,
    protein: 0.9,
    carbs: 7,
    fat: 0.3,
    fiber: 1.7,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['morango'],
  },
  {
    canonicalName: 'laranja',
    foodGroup: 'FRUIT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.2,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['laranja'],
  },
  {
    canonicalName: 'arroz branco cozido',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 128,
    protein: 2.5,
    carbs: 28.1,
    fat: 0.2,
    fiber: 1.6,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['arroz', 'arroz branco cozido'],
  },
  {
    canonicalName: 'arroz integral cozido',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 124,
    protein: 2.6,
    carbs: 25.8,
    fat: 1,
    fiber: 2.7,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['arroz integral', 'arroz integral cozido'],
  },
  {
    canonicalName: 'batata doce cozida',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 77,
    protein: 0.6,
    carbs: 18.4,
    fat: 0.1,
    fiber: 2.2,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['batata doce', 'batata doce cozida'],
  },
  {
    canonicalName: 'batata inglesa cozida',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 52,
    protein: 1.2,
    carbs: 12,
    fat: 0.1,
    fiber: 1.3,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['batata inglesa', 'batata cozida'],
  },
  {
    canonicalName: 'mandioca cozida',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 125,
    protein: 1,
    carbs: 30,
    fat: 0.3,
    fiber: 1.6,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['mandioca', 'mandioca cozida', 'aipim', 'macaxeira'],
  },
  {
    canonicalName: 'inhame cozido',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 97,
    protein: 2.1,
    carbs: 23,
    fat: 0.2,
    fiber: 3.1,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['inhame', 'inhame cozido'],
  },
  {
    canonicalName: 'aveia em flocos',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 394,
    protein: 13.9,
    carbs: 66,
    fat: 8.5,
    fiber: 9.1,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['aveia', 'aveia em flocos'],
  },
  {
    canonicalName: 'pao integral',
    foodGroup: 'CARB',
    baseAmount: 50,
    baseUnit: 'g',
    calories: 128,
    protein: 6,
    carbs: 21,
    fat: 2.2,
    fiber: 3.1,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['pao integral', 'pão integral'],
  },
  {
    canonicalName: 'tapioca',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 237,
    protein: 0.2,
    carbs: 58,
    fat: 0.1,
    fiber: 0.4,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['tapioca', 'goma de tapioca'],
  },
  {
    canonicalName: 'peito de frango grelhado',
    foodGroup: 'PROTEIN',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 159,
    protein: 32,
    carbs: 0,
    fat: 3,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['frango', 'peito de frango', 'peito de frango grelhado'],
  },
  {
    canonicalName: 'tilapia',
    foodGroup: 'PROTEIN',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 129,
    protein: 26,
    carbs: 0,
    fat: 2.7,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['tilapia', 'tilápia'],
  },
  {
    canonicalName: 'patinho moido',
    foodGroup: 'PROTEIN',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 170,
    protein: 26,
    carbs: 0,
    fat: 7,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['patinho', 'patinho moido', 'patinho moído'],
  },
  {
    canonicalName: 'ovo inteiro cozido',
    foodGroup: 'PROTEIN',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 146,
    protein: 13.3,
    carbs: 0.6,
    fat: 9.5,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['ovo', 'ovos', 'ovo cozido', 'ovos inteiros'],
  },
  {
    canonicalName: 'atum em agua',
    foodGroup: 'PROTEIN',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 116,
    protein: 25.5,
    carbs: 0,
    fat: 1,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['atum', 'atum em agua'],
  },
  {
    canonicalName: 'sardinha',
    foodGroup: 'PROTEIN',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 188,
    protein: 24,
    carbs: 0,
    fat: 10,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['sardinha'],
  },
  {
    canonicalName: 'iogurte natural',
    foodGroup: 'DAIRY',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 63,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['iogurte natural', 'iogurte'],
  },
  {
    canonicalName: 'leite desnatado',
    foodGroup: 'DAIRY',
    baseAmount: 100,
    baseUnit: 'ml',
    calories: 35,
    protein: 3.4,
    carbs: 5,
    fat: 0.2,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['leite desnatado', 'leite'],
  },
  {
    canonicalName: 'queijo minas frescal',
    foodGroup: 'DAIRY',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 264,
    protein: 17.4,
    carbs: 3.2,
    fat: 20.2,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['queijo minas', 'minas frescal', 'queijo minas frescal'],
  },
  {
    canonicalName: 'whey protein concentrado',
    foodGroup: 'DAIRY',
    baseAmount: 30,
    baseUnit: 'g',
    calories: 120,
    protein: 23,
    carbs: 3,
    fat: 2,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['whey', 'whey protein', 'whey protein concentrado'],
  },
  {
    canonicalName: 'castanha do para',
    foodGroup: 'NUT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 643,
    protein: 14.5,
    carbs: 15,
    fat: 63.5,
    fiber: 7.9,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['castanha do para', 'castanha-do-para', 'castanha do pará'],
  },
  {
    canonicalName: 'amendoim torrado',
    foodGroup: 'NUT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 606,
    protein: 22.5,
    carbs: 18.7,
    fat: 49.6,
    fiber: 7.8,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['amendoim', 'amendoim torrado'],
  },
  {
    canonicalName: 'amendoa',
    foodGroup: 'NUT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 581,
    protein: 18.6,
    carbs: 29.5,
    fat: 47.3,
    fiber: 11.6,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['amendoa', 'amêndoa', 'amendoas', 'amêndoas'],
  },
  {
    canonicalName: 'nozes',
    foodGroup: 'NUT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 620,
    protein: 14,
    carbs: 18,
    fat: 59,
    fiber: 6.7,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['nozes', 'noz'],
  },
  {
    canonicalName: 'azeite de oliva',
    foodGroup: 'FAT',
    baseAmount: 100,
    baseUnit: 'ml',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['azeite', 'azeite de oliva'],
  },
  {
    canonicalName: 'abacate',
    foodGroup: 'FAT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 96,
    protein: 1.2,
    carbs: 6,
    fat: 8.4,
    fiber: 6.3,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['abacate'],
  },
  {
    canonicalName: 'pasta de amendoim',
    foodGroup: 'FAT',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['pasta de amendoim', 'creme de amendoim'],
  },
  {
    canonicalName: 'creme de ricota',
    foodGroup: 'DAIRY',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 164,
    protein: 8,
    carbs: 5,
    fat: 12,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['creme de ricota', 'ricota cremosa'],
  },
  {
    canonicalName: 'feijao carioca cozido',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 76,
    protein: 4.8,
    carbs: 13.6,
    fat: 0.5,
    fiber: 8.5,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['feijao', 'feijão', 'feijao carioca', 'feijao carioca cozido'],
  },
  {
    canonicalName: 'lentilha cozida',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 93,
    protein: 6.3,
    carbs: 16.3,
    fat: 0.5,
    fiber: 7.9,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['lentilha', 'lentilha cozida'],
  },
  {
    canonicalName: 'grao de bico cozido',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 164,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    fiber: 7.6,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['grao de bico', 'grão de bico', 'grao de bico cozido'],
  },
  {
    canonicalName: 'cuscuz de milho cozido',
    foodGroup: 'CARB',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 112,
    protein: 2.3,
    carbs: 25.3,
    fat: 0.7,
    fiber: 1.7,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['cuscuz', 'cuscuz de milho', 'cuscuz de milho cozido'],
  },
  {
    canonicalName: 'carne bovina magra grelhada',
    foodGroup: 'PROTEIN',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 219,
    protein: 31,
    carbs: 0,
    fat: 10,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['carne magra', 'alcatra magra', 'carne bovina magra'],
  },
  {
    canonicalName: 'queijo cottage',
    foodGroup: 'DAIRY',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fat: 4.3,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['cottage', 'queijo cottage'],
  },
  {
    canonicalName: 'ricota fresca',
    foodGroup: 'DAIRY',
    baseAmount: 100,
    baseUnit: 'g',
    calories: 140,
    protein: 12.6,
    carbs: 3.8,
    fat: 8.1,
    fiber: 0,
    sourceType: 'CATALOG',
    sourceRef: 'tbca-taco:seed-v2',
    aliases: ['ricota', 'ricota fresca'],
  },
]

export class SeedFoodCatalogUseCase {
  constructor(private readonly foodCatalogRepository: FoodCatalogRepository) {}

  async execute(): Promise<void> {
    await this.foodCatalogRepository.upsertMany(MEDIUM_CURATED_CATALOG)
  }
}
