import type { FoodCatalogRepository } from '../../repositories/contracts/food-catalog-repository'

export class SeedFoodCatalogUseCase {
  constructor(private readonly foodCatalogRepository: FoodCatalogRepository) {}

  async execute(): Promise<void> {
    await this.foodCatalogRepository.upsertMany([
      {
        canonicalName: 'banana prata',
        foodGroup: 'FRUIT',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 98,
        protein: 1.3,
        carbs: 26,
        fat: 0.1,
        fiber: 2,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['banana', 'banana media', 'banana prata'],
      },
      {
        canonicalName: 'maca',
        foodGroup: 'FRUIT',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 84,
        protein: 0.3,
        carbs: 22,
        fat: 0.2,
        fiber: 2,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['maca', 'maça'],
      },
      {
        canonicalName: 'pera',
        foodGroup: 'FRUIT',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 96,
        protein: 0.4,
        carbs: 26,
        fat: 0.2,
        fiber: 3,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['pera'],
      },
      {
        canonicalName: 'goiaba',
        foodGroup: 'FRUIT',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 54,
        protein: 1,
        carbs: 13,
        fat: 0.4,
        fiber: 6,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['goiaba'],
      },
      {
        canonicalName: 'mamao',
        foodGroup: 'FRUIT',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 45,
        protein: 0.6,
        carbs: 11,
        fat: 0.1,
        fiber: 1.8,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['mamao', 'mamão'],
      },
      {
        canonicalName: 'arroz branco cozido',
        foodGroup: 'CARB',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 128,
        protein: 2.5,
        carbs: 28.1,
        fat: 0.2,
        fiber: 1.6,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['arroz', 'arroz branco cozido'],
      },
      {
        canonicalName: 'batata doce cozida',
        foodGroup: 'CARB',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 77,
        protein: 0.6,
        carbs: 18.4,
        fat: 0.1,
        fiber: 2.2,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['batata doce', 'batata doce cozida'],
      },
      {
        canonicalName: 'mandioca cozida',
        foodGroup: 'CARB',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 125,
        protein: 1,
        carbs: 30,
        fat: 0.3,
        fiber: 1.6,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['mandioca', 'mandioca cozida', 'aipim', 'macaxeira'],
      },
      {
        canonicalName: 'peito de frango grelhado',
        foodGroup: 'PROTEIN',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 159,
        protein: 32,
        carbs: 0,
        fat: 3,
        fiber: 0,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['frango', 'peito de frango', 'peito de frango grelhado'],
      },
      {
        canonicalName: 'tilapia',
        foodGroup: 'PROTEIN',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 129,
        protein: 26,
        carbs: 0,
        fat: 2.7,
        fiber: 0,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['tilapia', 'tilápia'],
      },
      {
        canonicalName: 'patinho moido',
        foodGroup: 'PROTEIN',
        baseAmount: 100,
        baseUnit: 'g',
        calories: 170,
        protein: 26,
        carbs: 0,
        fat: 7,
        fiber: 0,
        sourceType: 'CATALOG',
        sourceRef: 'seed:v1',
        aliases: ['patinho', 'patinho moido', 'patinho moído'],
      },
    ])
  }
}
